################################################################################
# runtime properties

# run updateConfig after changing these properties

ssaconfigBaseUrl=http://localhost:10000/servlets/detoxrcm

ssaconfigMysqlHost=detoxrcmdb
ssaconfigMysqlPort=3306
ssaconfigMysqlRootPassword=SECRET

ssaconfigDbNamePrefix=ssa
# 256 bit Base64 key
ssaconfigJwtSecretKey=SECRET
ssaconfigSecretSalt=SECRET

ssaconfigAdminEmail=SECRET
ssaconfigAdminPassword=SECRET

ssaconfigMailHost=localhost
ssaconfigMailUsername=
ssaconfigMailPassword=
ssaconfigMailSmtpTls=false
ssaconfigMailFrom=Detox@Home remote care manager <info@example.com>

ssaconfigTwilioAccountSid=ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
ssaconfigTwilioAuthToken=
ssaconfigTwilioVerifyServiceSid=VAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

ssaconfigWebUrl=http://localhost:10000/detoxrcm

ssaconfigDataDir=/var/log/detoxrcm

################################################################################
# deployment properties

dockerTomcatUser=SECRET
dockerTomcatPassword=SECRET
dockerLogDir=/var/log/detoxrcm
dockerContext=default
dockerProject=detoxrcm
dockerTag=latest
