# For this dockerignore file we assume that "docker build" is run from the git
# root directory. Paths in this file are relative from there.
#
# This file is used in two cases:
#
# - With the COPY command in Dockerfile. In this case it should be next to
#   Dockerfile as Dockerfile.dockerignore
#
# - When copying the workspace to a remote context. In this case it should be
#   at the git root directory.

**/
!detox-remote-care-manager/
**/.*/
!**/.htaccess
**/bin/
**/build/
**/node_modules/
detox-remote-care-manager/DataAccessObjects/
detox-remote-care-manager/ExampleSenSeeActClient/
detox-remote-care-manager/SenSeeActClient/
detox-remote-care-manager/SenSeeActServiceLib/
detox-remote-care-manager/ExampleSenSeeActService/docker/
!detox-remote-care-manager/ExampleSenSeeActService/docker/senseeactweb/
detox-remote-care-manager/ExampleSenSeeActService/src/
